export const iconKeys = [
  'air-vent',
  'battery-charging',
  'car-front',
  'circle-dot',
  'circle-gauge',
  'cog',
  'disc-3',
  'droplets',
  'file-check-2',
  'fuel',
  'gauge',
  'package-search',
  'paintbrush',
  'rotate-ccw',
  'route',
  'scan-search',
  'settings',
  'sparkles',
  'thermometer',
  'wind',
  'wrench',
  'zap',
  'plug',
  'triangle-exclamation',
  'magnifying-glass-chart',
] as const;

export type IconKey = (typeof iconKeys)[number];
