import { IconKey } from '@autoservice/contracts';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faBolt,
  faBoxOpen,
  faCar,
  faCarBattery,
  faCircleDot,
  faClipboardCheck,
  faCompactDisc,
  faDroplet,
  faFan,
  faGasPump,
  faGauge,
  faGaugeHigh,
  faGear,
  faGears,
  faMagnifyingGlass,
  faPaintRoller,
  faRotateLeft,
  faRoute,
  faTemperatureHalf,
  faWandMagicSparkles,
  faWind,
  faWrench,
  faPlug,
  faTriangleExclamation,
  faMagnifyingGlassChart,
} from '@fortawesome/free-solid-svg-icons';

export const iconMap = {
  'scan-search': faMagnifyingGlass,
  settings: faGears,
  'car-front': faCar,
  'disc-3': faCompactDisc,
  cog: faGear,
  zap: faBolt,
  'circle-gauge': faGaugeHigh,
  droplets: faDroplet,
  'circle-dot': faCircleDot,
  route: faRoute,
  'rotate-ccw': faRotateLeft,
  gauge: faGauge,
  'air-vent': faFan,
  thermometer: faTemperatureHalf,
  fuel: faGasPump,
  wind: faWind,
  'battery-charging': faCarBattery,
  'file-check-2': faClipboardCheck,
  'package-search': faBoxOpen,
  wrench: faWrench,
  paintbrush: faPaintRoller,
  sparkles: faWandMagicSparkles,
  plug: faPlug,
  'triangle-exclamation': faTriangleExclamation,
  'magnifying-glass-chart': faMagnifyingGlassChart,
} as const satisfies Record<IconKey, IconDefinition>;

export const defaultIcon: IconDefinition = faWrench;
